spring.application.name=pdf

server.port=9090
pdf.validation.vera-pdf-command=F:\\vera\\setup\\verapdf.bat
pdf.validation.vera-pdf-profile=ua2
pdf.validation.default-language=en-US

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB